# Miscellaneous
analitycs: UA-106429071-2
favicon: https://github.com/codermarcos/frontend-weekly/raw/assets/logo_frontend-weekly.ico
twitter: https://twitter.com/codermarcos
gmail: mailto:coder.marcos@gmail.com
github: https://github.com/codermarcos
facebook:
instagram:
linkedin: https://br.linkedin.com/in/codermarcos
youtube:
whatsapp: https://api.whatsapp.com/send?phone=5511971353293
